name: Continuous Integration

on:
  push:
    branches:
    - '**'

  pull_request:
    branches:
    - '**'

jobs:
  build-format-test:
    runs-on: ubuntu-24.04

    container:
        image: alexib1995/kettle-image
        options: --user root
    
    steps:
        - uses: actions/checkout@v4

        - name: Configure with CMake presets
          run: cmake --preset=dev

        - name: Build
          run: cmake --build --preset=dev

        - name: Run codespell
          run: cmake --build --preset=dev -t spell-check

        - name: Clang-format check
          run: cmake --build --preset=dev -t format-check

        - name: Run unit tests
          run: ctest --preset=dev --output-on-failure
